kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backend-stateful-app-storage-backend-set-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
