apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-stateful-app-storage-backend-set-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /hms/data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube # this must be the name of your node(kubectl get nodes)

