apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    tier: backend-app
    env: dev
    app: mysql
    release-date: 24-Apr-2022
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: sansoft/test-kube-backend:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Asia/Colombo"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_POST
              value: "3306"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName


      
    
