apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-set
spec:
  selector:
    matchLabels:
      app: backend-stateful-app
  serviceName: "backend-stateful-app-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: backend-stateful-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: backend-stateful-app
          image: sansoft/test-kube-backend:0.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: backend-stateful-app-storage
              mountPath: /hms/logs
              readOnly: false
          env:
            - name: TZ
              value: "Asia/Colombo"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_POST
              value: "3306"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
  volumeClaimTemplates:
    - metadata:
        name: backend-stateful-app-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 2Gi