apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    tier: backend
    env: dev
    app: mysql
    release-date: 22-Apr-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-mysql
  template:
    metadata:
      labels:
        app: app-mysql
    spec:
      containers:
        - name: app-mysql
          image: sansoft/mysql:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: app_db
            - name: TZ
              value: Asia/Colombo
            - name: TEST
              value: test
